import React from 'react'

const contact = () => {
  return (
    <div>contact</div>
  )
}

export default contact
export const metadata = {
    title: "Next JS - Contact",
    description: "Generated by create next app",
  };