import Image from 'next/image';
import React from 'react'

const about = () => {
  return (
    <div className='container relative w-full h-96'>
        <Image className='mx-auto mt-5' src={`https://img.freepik.com/free-photo/painting-mountain-lake-with-mountain-background_188544-9126.jpg`} alt='image' fill={true} />
    </div>
  )
}

export default about

export const metadata = {
    title: "Next JS - About",
    description: "Generated by create next app",
  };