export const metadata = {
  title: "Next JS - Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <div className="relative">
    <p className="text-xs absolute right-0">Admin</p>
        {children}
        {/* By adding Brackets to admin we don't have to write admin/profile, it helps to grouping the pages */}
    </div>   
  );
}
